# Generated by Django 3.0.3 on 2020-02-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula05', '0002_categoria_comentario_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtos', models.ManyToManyField(related_name='carrinhos', to='aula05.Produto')),
            ],
        ),
    ]
